### ISSUE TITLE
code.h: No such file or directory

### ISSUE THREAD

**Issue by BullyWiiPlaza** [jam1garner/diibugger-cli#2]
You probably forgot to commit some of the source files like `code.h` but thanks for this port. 👍 

`> make
main.c
d:/Diibugger-cli/src/main.c:7:18: fatal error: code.h: No such file or directory
 #include "code.h"
                  ^
compilation terminated.
make[1]: *** [main.o] Error 1
make: *** [build] Error 2`

**Comment by jam1garner** [comment]
Run "build.bat" or "build.sh" as it compiles the binary stored in code.h before running make, which is installed by the "installer" when you first run it. I know this isn't the cleanest way to do it but uh heh.
